### ISSUE TITLE
'Namespace' object has no attribute 'r_mean'

### ISSUE THREAD

**Issue by BigChen28** [JiahuiYu/wdsr_ntire2018#10]
Hi, thank you very much for sharing your code.
I ran your model(WDSR_b ) based on EDSR-Pytorch as backbone training framework, but it reported an error as follows:

AttributeError: 'Namespace' object has no attribute 'r_mean'

The relevant code is located in wdsr-b.py:
self.rgb_mean = torch.autograd.Variable(torch.FloatTensor(
            [args.r_mean, args.g_mean, args.b_mean])).view([1, 3, 1, 1])

And I can't find the values of r_mean,g_mean and b_mean in option.py, so could you tell how to set these values?

**Comment by JiahuiYu** [comment]
Please find the result in issue #7

**Comment by BigChen28** [comment]
I am sorry that I did not see your reply and thank you very much for your answer.

**Comment by JiahuiYu** [comment]
@BigChen28 No problem, let me know if you have further questions.
