### ISSUE TITLE
Wide-activation

### ISSUE THREAD

**Issue by DanChen001** [JiahuiYu/wdsr_ntire2018#11]
Hi, 

Thank you for providing the code.

The wide-activated network is very effective. Do you have idea why it works?  Thanks.

**Comment by JiahuiYu** [comment]
@DanChen001 The wide activation rule is mainly based on several motivations. One motivation is that non-linear ReLUs impede information flow from shallow layers to deeper ones, as mentioned in our [report](https://arxiv.org/abs/1808.08718).

**Comment by DanChen001** [comment]
@JiahuiYu   Thanks.
