### ISSUE TITLE
results

### ISSUE THREAD

**Issue by taniaCHY** [JiahuiYu/wdsr_ntire2018#13]
Can you send me the result of the DIV2K verification?E-mail: 1970915834 @qq.com

**Comment by JiahuiYu** [comment]
@taniaCHY What you mean by DIV2K verification? Validation results?

**Comment by taniaCHY** [comment]
Yes，Due to time, I have no time to run the experiment of EDSR, so could you please send me the result of the test with div2k? I want to compare the results of my experiment when I write my paper

**Comment by JiahuiYu** [comment]
@taniaCHY I only have results of [bicubic x8](https://drive.google.com/open?id=12Ak8ehsCo50dXJr2ORhszQaEdLI_S9I9).

**Comment by taniaCHY** [comment]
There is no bicubic x4？I tried to run the code with pytorch, but I didn't know how to change the option.py file code.

**Comment by JiahuiYu** [comment]
@taniaCHY I have not saved any x4 models or results.
