### ISSUE TITLE
Overall Performance table2' questions

### ISSUE THREAD

**Issue by ChaofWang** [JiahuiYu/wdsr_ntire2018#16]
hello, Jiahui. I want to reproduce the results of table2. But I found that the amount of parameters in your table seems to be 10 times larger. I think maybe this is a writing mistake, is that right?  For example，I set  n_resblocks = 1，n_feats = 64，scale = [2]， rgb_range = 255，res_scale = 1，n_colors =3 for EDSR，and total parameters is 262,043, not 2.6M， is this correct?

**Comment by JiahuiYu** [comment]
@ChaofWang Hi, thanks a lot for your report. Yes you are correct. EDSR is 262043 while WDSR is 79380. Our conclusion is same but we will correct this soon. Thanks!
