### ISSUE TITLE
The difference between nn.PixelShuffle and nn.ConvTranspose2d ?

### ISSUE THREAD

**Issue by YongboLiang** [JiahuiYu/wdsr_ntire2018#18]
Hi, I have a doubt about nn.PixelShuffle and nn.ConvTranspose2d. In the upsampling layer, some use nn.PixelShuffle while others use nn.ConvTranspose2d. The number of filters belong to nn.PixelShuffle is scale^2 times that of  number of filters belong to nn.ConvTranspose2d. However, I don't find any authors describing the difference between the two methods in their paper.

Have you thought about this and experimented? Will these two methods have an impact on the training results?

Best~

**Comment by JiahuiYu** [comment]
Real-Time Single Image and Video Super-Resolution Using an Efficient Sub-Pixel Convolutional Neural Network

https://arxiv.org/abs/1609.05158
