### ISSUE TITLE
I put the two model files in that directory, but I need to configure what parameters to let him access the model file.

### ISSUE THREAD

**Issue by JusperLee** [JiahuiYu/wdsr_ntire2018#23]

**Comment by JiahuiYu** [comment]
An implementation issue is beyond the scope of repo.

**Comment by JusperLee** [comment]
I still have a question. When your model is configured, does cuda exceed memory?

**Comment by JusperLee** [comment]
@JiahuiYu Thank you, I would like to ask you what python parameters are used in the configuration, I hope to learn from it.

**Comment by JusperLee** [comment]
@JiahuiYu this is my option.
![image](https://user-images.githubusercontent.com/33806018/51757224-cc6cae00-20fd-11e9-9cea-7bfd2026f24b.png)

**Comment by JiahuiYu** [comment]
@JusperLee It looks good. For us, we use V100 and the CUDA memory is fine.
