### ISSUE TITLE
Testing the models

### ISSUE THREAD

**Issue by gitman88** [JiahuiYu/wdsr_ntire2018#28]
What would the terminal command be to evaluate the WDSR models with EDSR as backbone?

I added the following to the option.py

`parser.add_argument('--r_mean', type=float, default=0.4488,
                    help='Mean of R Channel')
parser.add_argument('--g_mean', type=float, default=0.4371,
                    help='Mean of G channel')
parser.add_argument('--b_mean', type=float, default=0.4040,
                    help='Mean of B channel')
parser.add_argument('--block_feats', type=int, default=128,
                    help='Block feats')`

And added the wdsr_a and wdsr_b models to src/model/. 

What would the corresponding command for the WDSR be something like this:

`python main.py --data_test Set5 --data_range 801-900 --scale 4 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --pre_train download --test_only --self_ensemble`

Any help appreciated!

**Comment by JiahuiYu** [comment]
It should be similar to EDSR testing command.

**Comment by gitman88** [comment]
Well, it evaluates the data by reporting a nan as PSNR. The data is located at src/data/benchmark and the path in option.py looks like this:

`
parser.add_argument('--dir_data', type=str, default='/Users/Dev/EDSR-PyTorch/src/data/benchmark',
                    help='dataset directory')
parser.add_argument('--dir_demo', type=str, default='../test',
                    help='demo image directory')
parser.add_argument('--data_train', type=str, default='B100',
                    help='train dataset name')
parser.add_argument('--data_test', type=str, default='B100',
                    help='test dataset name')`

When running the output is this:


`Evaluation:
0it [00:00, ?it/s]
[Set5 x4]	PSNR: nan (Best: nan @epoch 1)
0it [00:00, ?it/s]
[Set14 x4]	PSNR: nan (Best: nan @epoch 1)
0it [00:00, ?it/s]
[B100 x4]	PSNR: nan (Best: nan @epoch 1)
0it [00:00, ?it/s]
[Urban100 x4]	PSNR: nan (Best: nan @epoch 1)
0it [00:00, ?it/s]
[DIV2K x4]	PSNR: nan (Best: nan @epoch 1)
Forward: 0.50s

Saving...
Total: 0.50s`

Any ideas what could cause this?

**Comment by JiahuiYu** [comment]
I have no related experiences on this issue. I would suggest to print out predicted images (and maybe feature map) to debug.

**Comment by Ccbov** [comment]
> Well, it evaluates the data by reporting a nan as PSNR. The data is located at src/data/benchmark and the path in option.py looks like this:
> 
> `parser.add_argument('--dir_data', type=str, default='/Users/Dev/EDSR-PyTorch/src/data/benchmark', help='dataset directory')`
> `parser.add_argument('--dir_demo', type=str, default='../test', help='demo image directory')`
> `parser.add_argument('--data_train', type=str, default='B100', help='train dataset name')`
> `parser.add_argument('--data_test', type=str, default='B100', help='test dataset name')`
> 
> When running the output is this:
> 
> `Evaluation:
> 0it [00:00, ?it/s]
> [Set5 x4] PSNR: nan (Best: nan @epoch 1)
> 0it [00:00, ?it/s]
> [Set14 x4] PSNR: nan (Best: nan @epoch 1)
> 0it [00:00, ?it/s]
> [B100 x4] PSNR: nan (Best: nan @epoch 1)
> 0it [00:00, ?it/s]
> [Urban100 x4] PSNR: nan (Best: nan @epoch 1)
> 0it [00:00, ?it/s]
> [DIV2K x4] PSNR: nan (Best: nan @epoch 1)
> Forward: 0.50s
> 
> Saving...
> Total: 0.50s`
> 
> Any ideas what could cause this?

hello, I meet the same problem, could you please give me some advise?
