### ISSUE TITLE
Testing on "wild LR" = track 3 NTIRE2018

### ISSUE THREAD

**Issue by sefibk** [JiahuiYu/wdsr_ntire2018#29]
Hi,
Could you please explain if and how can I run your network on images from track3 of the challenge? 
I am interested in the test\inference stage (not the training).
Would this work also on any image I choose at random or is it limited in some sense?

Thank you

**Comment by JiahuiYu** [comment]
Hi, you can test on any image. Please follow EDSR-Pytorch README for instructions on how to do inference.
