### ISSUE TITLE
How to reduce inference time

### ISSUE THREAD

**Issue by dongxijia** [JiahuiYu/wdsr_ntire2018#30]
Hello, Thanks for your sharing!
I followed the steps to train WDSR-b model with --resblock 8 and --n_feats 64 , and got 34.755 PSNR on  DIV2K 801~900 photos. 
My inference time is  1.1 seconds in 1080Ti for 1020×678 to 2040×1356, I would like to know if there is  any way to reduce the inference time when network' s parameters are constant. 
I am looking forward for you reply, thanks a lot!

**Comment by JiahuiYu** [comment]
I don’t think there is anyway to speed up.
