### ISSUE TITLE
I didn't get desired training result

### ISSUE THREAD

**Issue by vhank** [JiahuiYu/wdsr_ntire2018#31]
Hi,I trained WDSR_A model on DIV2K_wild_x4 training set,but the final test PSNR is about 19.423.Is the result worse than yours?Here's some of my settings,and could you please help me check whether my setting is correct. 
1.trainging dataset：3200 wild LR images(I mixed 800x4 wild LR images),test dataset:100 wild LR images
2.parameters:
--model wdsr_a --scale 4  --batch_size=64  --patch_size 192  --data_range '1-3200/3201-3300' 
 --n_feats 128 --block_feats 512 --lr 1e-4 --reset

**Comment by JiahuiYu** [comment]
@vhank Hi, the results in this code and our report is based on x2 bicubic SR. For our challenge submission last year, I remember we use following settings train on one V100 for 14 days.

```
# bicubic x8
--n_resblocks 32 --n_feats 128 --block_feats 512 --res_scale 0.1 --lr 0.001 --lr_decay 200 --patch_size 384

# wild x4
--n_resblocks 32 --n_feats 128 --block_feats 256 --res_scale 0.1 --lr 0.001 --lr_decay 100 --patch_size 192
```

**Comment by 363325971** [comment]
@JiahuiYu Hi, comparing with the keras implementation,  what is the corresponding parametes with n_feats, block_feats and patch_size?

**Comment by JiahuiYu** [comment]
@363325971 which keras implementation? We don't have any official keras version of WDSR.
