### ISSUE TITLE
How to achieve the results in the paper?

### ISSUE THREAD

**Issue by Zysty** [JiahuiYu/wdsr_ntire2018#33]
hi jiahui. I want to reproduce your WDSRA  x2 result 34.541 dB. I used EDSR-Pytorch framework to train and set   --patch_size 96  --n_resblocks 8 --n_feats 32 --block_feats 128 --res_scale 1 .
All results are lower than yours, can you tell me the settings of other hyperparameters for your training?Thanks.

**Comment by JiahuiYu** [comment]
Hi,

Please refer to tensorflow implementation, which has both training and testing code.
