### ISSUE TITLE
About the linear low-rank convolution 

### ISSUE THREAD

**Issue by yiyunchen** [JiahuiYu/wdsr_ntire2018#35]
In the paper, it said that linear low-rank convolution  factorizes a large convolution kernel to two low-rank convolution kernels. 
but i did not see the detailed, and i am confused about it. i would like to know which part of the code is for this.
i am new to this.
Thank you!

**Comment by JiahuiYu** [comment]
https://github.com/JiahuiYu/wdsr_ntire2018/blob/cd2053e20579a020f609459d795656590dc98307/wdsr_b.py#L18-L21
