### ISSUE TITLE
I got a result image of all gray with no contents 

### ISSUE THREAD

**Issue by jxingm** [JiahuiYu/wdsr_ntire2018#39]
Hi,thanks for your code.I want test one single image of my own with MDSR(x4),and I did something like this:
1. Add in option.py:
`# Option for WDSR                   
parser.add_argument('--r_mean', type=float, default=0.4488,
                    help='Mean of R Channel')
parser.add_argument('--g_mean', type=float, default=0.4371,
                    help='Mean of G channel')
parser.add_argument('--b_mean', type=float, default=0.4040,
                    help='Mean of B channel')                    
parser.add_argument('--block_feats', type=int, default=128, help='Block feats') `

2. move wdsr_a.py,wdsr_b.py to model

3. use the lines in demo.sh like this and comment others:
`python main.py --data_test Demo --scale 4 --pre_train ../experiment/model/MDSR_baseline.pt --test_only --save_results`
4. run command 'sh demo.sh'

Last I got an image of all gray with nothing,no color,no cotent, I need some help to know where the issue is.

**Comment by JiahuiYu** [comment]
I guess you need to train your WDSR first, before testing?

**Comment by jxingm** [comment]
> I guess you need to train your WDSR first, before testing?

Thanks for your reply.
But the model MDSR_baseline.pt is a pre-trained model, isn't it?  Maybe I can't use it directly to test,you mean that?

**Comment by JiahuiYu** [comment]
MDSR_baseline.pt is not our trained model for WDSR, right?
