### ISSUE TITLE
WDSR-A  vs. WDSR-B

### ISSUE THREAD

**Issue by DanChen001** [JiahuiYu/wdsr_ntire2018#4]
Hi, Jiahui,
 
Thank you for sharing the code.

Did you compare the performance  of WDSR-A and WDSR-B when the number of resiudal blocks is larger than 8？

It seems that the WDSR-B is more effective than WDSR-A when the resiudal blocks are very few.

Thanks

**Comment by JiahuiYu** [comment]
@DanChen001 Hi, first thank you for your interest and investigation on our work. We mainly aim at efficient models for SR, for which we propose WDSR-A and WDSR-B. For accuracy (PSNR) only, I guess the model architecture does not matter a lot, as long as one stacks many many residual blocks (e.g., a very large EDSR may perform similarly to large WDSR-A or WDSR-B).

**Comment by DanChen001** [comment]
@JiahuiYu   Thank you for the reply.
