### ISSUE TITLE
Ablation study for WDSR-B

### ISSUE THREAD

**Issue by hobin-jeong** [JiahuiYu/wdsr_ntire2018#41]
Hello, @JiahuiYu ! 

I'm trying to implement your network.

When I checked your light models for WDSR-B, I found the difference between your results and my results. I saying WDSR-B with n resblocks as WDSR-B_nblks, you assert that the numbers of parameters of WDSR-A_nblks and WDSR-B_nblks are equal. ( e.g. the number of parameters of WDSR-A_1blks and WDSR-B_1blks is 0.08M )

According to my computation, the numbers of parameters of WDSR-A_nblks are almost equal, but those of WDSR-B_nblks are quite different. ( more precisely, my results are less than yours )

How to compute the number of parameters?
I use this formula: kernel_size^2 * ch_in * ch_out (weight) + ch_out (bias) for each convolution.

Thanks in advance!

Hobin

**Comment by JiahuiYu** [comment]
@hobin-jeong Hi, we directly print the number of trainable parameters instead of manually calculate it - so our numbers should be correct. Moreover your formula should be correct for each convolution - please carefully checkout the `ch_in` and `ch_out` in our WDSR-B.
