### ISSUE TITLE
In WDSR-B, why not do the 3x3 Conv without the second 1x1 Conv?

### ISSUE THREAD

**Issue by splinter21** [JiahuiYu/wdsr_ntire2018#43]
WDSR-A
x/2->2x->x/2
computation:
3x3x2/2+3x3x2/2=18
act:
2
3x3Conv:
100%

WDSR-B:
x->6x->0.8x->x
computation:
6+6x0.8+3x3x0.8=18
act:
6
3x3Conv:
40%
(I think you use the second 1x1 Conv just to align the computation with one EDSR block and WDSR-A block)

WDSR-B-modified:
x/2->3x->x/2
computation:
3/2+3/2x3x3=15
act:
3
3x3Conv:
90%
So you can compare the performance: WDSR-A-B5 vs. WDSR-B-modified-B6.

**Comment by JiahuiYu** [comment]
@splinter21 I guess you can have a try.  Do you have any performance evaluation?
