### ISSUE TITLE
About train x4 model

### ISSUE THREAD

**Issue by yyk722** [JiahuiYu/wdsr_ntire2018#5]
Hi, Jiahui,

Thank you for sharing.
I am trying to implement the wdsr_a x4 and I would like to know whether the number of block_feats is 4 time of the n_feats and is it necessary to train a wdsr_a x2 model and set it as the pre_train of the wdsr_a x4?

Thanks

**Comment by JiahuiYu** [comment]
@yyk722 Yes. We use block_feats 4x of the n_feats for training x4 super-resolution. We did not use x2 model as pertained weights for x4. But it worths trying since EDSR uses the pre-trained models.

**Comment by yyk722** [comment]
Thanks
