### ISSUE TITLE
The value of n_feats

### ISSUE THREAD

**Issue by YongboLiang** [JiahuiYu/wdsr_ntire2018#6]
Hi, Jiahui,
Thanks for your sharing.

When you compare EDSR and WDSR, are the the values of n_feats the same and whether both values are set to 64？

Thanks.

**Comment by JiahuiYu** [comment]
Hi, in WDSR, we use 32-128 setting, which has similar FLOPs with EDSR 64.

**Comment by suke27** [comment]
@JiahuiYu, do you means for wdsr_a you always use 32-128 setting for x2,3,4 scale?

**Comment by JiahuiYu** [comment]
We use 32-128 for x2.
