### ISSUE TITLE
n_feats and block_feats for x4

### ISSUE THREAD

**Issue by bensuucar** [JiahuiYu/wdsr_ntire2018#8]
Hi, Jiahui,

I am trying to implement wdsr_a with the scale 4. I would like to compare its performance with EDSR( # of residual blocks = 32, n_feats = 256). In this case, what would be your recommendation to set n_feats and block_feats? 
Currently I am using wdsr_a with n_feats 128 and block_feats 512. However I am not sure if it is the intended approach while constructing the network.

**Comment by JiahuiYu** [comment]
Hi, @bensuucar, you are correct - n_feats 128 and block_feats 512 is a good choice, compared with EDSR of channel number 256.
