### ISSUE TITLE
How to set the r_mean, g_mean, b_mean attribute values of args?

### ISSUE THREAD

**Issue by BigChen28** [JiahuiYu/wdsr_ntire2018#9]
Hello,thank you very much for sharing your code.
I ran your model(WDSR_B) based on EDSR-Pytorch as backbone training framework, but when I ran here:

self.rgb_mean = torch.autograd.Variable(torch.FloatTensor(
            [args.r_mean, args.g_mean, args.b_mean])).view([1, 3, 1, 1])

I found the following errors:
AttributeError: 'Namespace' object has no attribute 'r_mean'

and I can't find the values of r_mean,g_mean,b_mean in the option.py, could you tell me how to set the values of r_mean,g_mean,b_mean?

**Comment by JiahuiYu** [comment]
#7 Please find the result in issue #7
